package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangRegion;
import com.baijuvip.jinxiang.db.domain.JinxiangRegionExample;

public interface JinxiangRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    long countByExample(JinxiangRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    int insert(JinxiangRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    JinxiangRegion selectOneByExample(JinxiangRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    JinxiangRegion selectOneByExampleSelective(@Param("example") JinxiangRegionExample example, @Param("selective") JinxiangRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    List<JinxiangRegion> selectByExampleSelective(@Param("example") JinxiangRegionExample example, @Param("selective") JinxiangRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    List<JinxiangRegion> selectByExample(JinxiangRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    JinxiangRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    JinxiangRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangRegion record, @Param("example") JinxiangRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangRegion record, @Param("example") JinxiangRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangRegion record);
}