package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangComment;
import com.baijuvip.jinxiang.db.domain.JinxiangCommentExample;

public interface JinxiangCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    long countByExample(JinxiangCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    int insert(JinxiangComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    JinxiangComment selectOneByExample(JinxiangCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    JinxiangComment selectOneByExampleSelective(@Param("example") JinxiangCommentExample example, @Param("selective") JinxiangComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    List<JinxiangComment> selectByExampleSelective(@Param("example") JinxiangCommentExample example, @Param("selective") JinxiangComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    List<JinxiangComment> selectByExample(JinxiangCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    JinxiangComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    JinxiangComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    JinxiangComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangComment record, @Param("example") JinxiangCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangComment record, @Param("example") JinxiangCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}