package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangAdmin;
import com.baijuvip.jinxiang.db.domain.JinxiangAdminExample;

public interface JinxiangAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    long countByExample(JinxiangAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    int insert(JinxiangAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    JinxiangAdmin selectOneByExample(JinxiangAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    JinxiangAdmin selectOneByExampleSelective(@Param("example") JinxiangAdminExample example, @Param("selective") JinxiangAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    List<JinxiangAdmin> selectByExampleSelective(@Param("example") JinxiangAdminExample example, @Param("selective") JinxiangAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    List<JinxiangAdmin> selectByExample(JinxiangAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    JinxiangAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    JinxiangAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    JinxiangAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangAdmin record, @Param("example") JinxiangAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangAdmin record, @Param("example") JinxiangAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}