package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangIssue;
import com.baijuvip.jinxiang.db.domain.JinxiangIssueExample;

public interface JinxiangIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    long countByExample(JinxiangIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    int insert(JinxiangIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    JinxiangIssue selectOneByExample(JinxiangIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    JinxiangIssue selectOneByExampleSelective(@Param("example") JinxiangIssueExample example, @Param("selective") JinxiangIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    List<JinxiangIssue> selectByExampleSelective(@Param("example") JinxiangIssueExample example, @Param("selective") JinxiangIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    List<JinxiangIssue> selectByExample(JinxiangIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    JinxiangIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    JinxiangIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    JinxiangIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangIssue record, @Param("example") JinxiangIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangIssue record, @Param("example") JinxiangIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}