package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangOrder;
import com.baijuvip.jinxiang.db.domain.JinxiangOrderExample;

public interface JinxiangOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    long countByExample(JinxiangOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    int insert(JinxiangOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    JinxiangOrder selectOneByExample(JinxiangOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    JinxiangOrder selectOneByExampleSelective(@Param("example") JinxiangOrderExample example, @Param("selective") JinxiangOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    List<JinxiangOrder> selectByExampleSelective(@Param("example") JinxiangOrderExample example, @Param("selective") JinxiangOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    List<JinxiangOrder> selectByExample(JinxiangOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    JinxiangOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    JinxiangOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    JinxiangOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangOrder record, @Param("example") JinxiangOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangOrder record, @Param("example") JinxiangOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}