package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangAd;
import com.baijuvip.jinxiang.db.domain.JinxiangAdExample;

public interface JinxiangAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    long countByExample(JinxiangAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    int insert(JinxiangAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    JinxiangAd selectOneByExample(JinxiangAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    JinxiangAd selectOneByExampleSelective(@Param("example") JinxiangAdExample example, @Param("selective") JinxiangAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    List<JinxiangAd> selectByExampleSelective(@Param("example") JinxiangAdExample example, @Param("selective") JinxiangAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    List<JinxiangAd> selectByExample(JinxiangAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    JinxiangAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    JinxiangAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    JinxiangAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangAd record, @Param("example") JinxiangAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangAd record, @Param("example") JinxiangAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}