package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangCategory;
import com.baijuvip.jinxiang.db.domain.JinxiangCategoryExample;

public interface JinxiangCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    long countByExample(JinxiangCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    int insert(JinxiangCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    JinxiangCategory selectOneByExample(JinxiangCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    JinxiangCategory selectOneByExampleSelective(@Param("example") JinxiangCategoryExample example, @Param("selective") JinxiangCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    List<JinxiangCategory> selectByExampleSelective(@Param("example") JinxiangCategoryExample example, @Param("selective") JinxiangCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    List<JinxiangCategory> selectByExample(JinxiangCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    JinxiangCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    JinxiangCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    JinxiangCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangCategory record, @Param("example") JinxiangCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangCategory record, @Param("example") JinxiangCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}