package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangRole;
import com.baijuvip.jinxiang.db.domain.JinxiangRoleExample;

public interface JinxiangRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    long countByExample(JinxiangRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    int insert(JinxiangRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    JinxiangRole selectOneByExample(JinxiangRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    JinxiangRole selectOneByExampleSelective(@Param("example") JinxiangRoleExample example, @Param("selective") JinxiangRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    List<JinxiangRole> selectByExampleSelective(@Param("example") JinxiangRoleExample example, @Param("selective") JinxiangRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    List<JinxiangRole> selectByExample(JinxiangRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    JinxiangRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    JinxiangRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    JinxiangRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangRole record, @Param("example") JinxiangRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangRole record, @Param("example") JinxiangRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}