package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangTopic;
import com.baijuvip.jinxiang.db.domain.JinxiangTopicExample;

public interface JinxiangTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    long countByExample(JinxiangTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int insert(JinxiangTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    JinxiangTopic selectOneByExample(JinxiangTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    JinxiangTopic selectOneByExampleSelective(@Param("example") JinxiangTopicExample example, @Param("selective") JinxiangTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    JinxiangTopic selectOneByExampleWithBLOBs(JinxiangTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    List<JinxiangTopic> selectByExampleSelective(@Param("example") JinxiangTopicExample example, @Param("selective") JinxiangTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    List<JinxiangTopic> selectByExampleWithBLOBs(JinxiangTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    List<JinxiangTopic> selectByExample(JinxiangTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    JinxiangTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    JinxiangTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    JinxiangTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangTopic record, @Param("example") JinxiangTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") JinxiangTopic record, @Param("example") JinxiangTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangTopic record, @Param("example") JinxiangTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(JinxiangTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}