package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangBrand;
import com.baijuvip.jinxiang.db.domain.JinxiangBrandExample;

public interface JinxiangBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    long countByExample(JinxiangBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    int insert(JinxiangBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    JinxiangBrand selectOneByExample(JinxiangBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    JinxiangBrand selectOneByExampleSelective(@Param("example") JinxiangBrandExample example, @Param("selective") JinxiangBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    List<JinxiangBrand> selectByExampleSelective(@Param("example") JinxiangBrandExample example, @Param("selective") JinxiangBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    List<JinxiangBrand> selectByExample(JinxiangBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    JinxiangBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    JinxiangBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    JinxiangBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangBrand record, @Param("example") JinxiangBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangBrand record, @Param("example") JinxiangBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}