package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangAddress;
import com.baijuvip.jinxiang.db.domain.JinxiangAddressExample;

public interface JinxiangAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    long countByExample(JinxiangAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    int insert(JinxiangAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    JinxiangAddress selectOneByExample(JinxiangAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    JinxiangAddress selectOneByExampleSelective(@Param("example") JinxiangAddressExample example, @Param("selective") JinxiangAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    List<JinxiangAddress> selectByExampleSelective(@Param("example") JinxiangAddressExample example, @Param("selective") JinxiangAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    List<JinxiangAddress> selectByExample(JinxiangAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    JinxiangAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    JinxiangAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    JinxiangAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangAddress record, @Param("example") JinxiangAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangAddress record, @Param("example") JinxiangAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}