package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangFeedback;
import com.baijuvip.jinxiang.db.domain.JinxiangFeedbackExample;

public interface JinxiangFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    long countByExample(JinxiangFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    int insert(JinxiangFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    JinxiangFeedback selectOneByExample(JinxiangFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    JinxiangFeedback selectOneByExampleSelective(@Param("example") JinxiangFeedbackExample example, @Param("selective") JinxiangFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    List<JinxiangFeedback> selectByExampleSelective(@Param("example") JinxiangFeedbackExample example, @Param("selective") JinxiangFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    List<JinxiangFeedback> selectByExample(JinxiangFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    JinxiangFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    JinxiangFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    JinxiangFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangFeedback record, @Param("example") JinxiangFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangFeedback record, @Param("example") JinxiangFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}