package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangFootprint;
import com.baijuvip.jinxiang.db.domain.JinxiangFootprintExample;

public interface JinxiangFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    long countByExample(JinxiangFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    int insert(JinxiangFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    JinxiangFootprint selectOneByExample(JinxiangFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    JinxiangFootprint selectOneByExampleSelective(@Param("example") JinxiangFootprintExample example, @Param("selective") JinxiangFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    List<JinxiangFootprint> selectByExampleSelective(@Param("example") JinxiangFootprintExample example, @Param("selective") JinxiangFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    List<JinxiangFootprint> selectByExample(JinxiangFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    JinxiangFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    JinxiangFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    JinxiangFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangFootprint record, @Param("example") JinxiangFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangFootprint record, @Param("example") JinxiangFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}