package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangCart;
import com.baijuvip.jinxiang.db.domain.JinxiangCartExample;

public interface JinxiangCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    long countByExample(JinxiangCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    int insert(JinxiangCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    JinxiangCart selectOneByExample(JinxiangCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    JinxiangCart selectOneByExampleSelective(@Param("example") JinxiangCartExample example, @Param("selective") JinxiangCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    List<JinxiangCart> selectByExampleSelective(@Param("example") JinxiangCartExample example, @Param("selective") JinxiangCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    List<JinxiangCart> selectByExample(JinxiangCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    JinxiangCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    JinxiangCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    JinxiangCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangCart record, @Param("example") JinxiangCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangCart record, @Param("example") JinxiangCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}