package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangPermission;
import com.baijuvip.jinxiang.db.domain.JinxiangPermissionExample;

public interface JinxiangPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    long countByExample(JinxiangPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    int insert(JinxiangPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    JinxiangPermission selectOneByExample(JinxiangPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    JinxiangPermission selectOneByExampleSelective(@Param("example") JinxiangPermissionExample example, @Param("selective") JinxiangPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    List<JinxiangPermission> selectByExampleSelective(@Param("example") JinxiangPermissionExample example, @Param("selective") JinxiangPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    List<JinxiangPermission> selectByExample(JinxiangPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    JinxiangPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    JinxiangPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    JinxiangPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangPermission record, @Param("example") JinxiangPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangPermission record, @Param("example") JinxiangPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}