package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangOrderGoods;
import com.baijuvip.jinxiang.db.domain.JinxiangOrderGoodsExample;

public interface JinxiangOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    long countByExample(JinxiangOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    int insert(JinxiangOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    JinxiangOrderGoods selectOneByExample(JinxiangOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    JinxiangOrderGoods selectOneByExampleSelective(@Param("example") JinxiangOrderGoodsExample example, @Param("selective") JinxiangOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    List<JinxiangOrderGoods> selectByExampleSelective(@Param("example") JinxiangOrderGoodsExample example, @Param("selective") JinxiangOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    List<JinxiangOrderGoods> selectByExample(JinxiangOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    JinxiangOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    JinxiangOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    JinxiangOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangOrderGoods record, @Param("example") JinxiangOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangOrderGoods record, @Param("example") JinxiangOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}