package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangKeyword;
import com.baijuvip.jinxiang.db.domain.JinxiangKeywordExample;

public interface JinxiangKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    long countByExample(JinxiangKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    int insert(JinxiangKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    JinxiangKeyword selectOneByExample(JinxiangKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    JinxiangKeyword selectOneByExampleSelective(@Param("example") JinxiangKeywordExample example, @Param("selective") JinxiangKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    List<JinxiangKeyword> selectByExampleSelective(@Param("example") JinxiangKeywordExample example, @Param("selective") JinxiangKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    List<JinxiangKeyword> selectByExample(JinxiangKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    JinxiangKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    JinxiangKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    JinxiangKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangKeyword record, @Param("example") JinxiangKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangKeyword record, @Param("example") JinxiangKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}