package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangLog;
import com.baijuvip.jinxiang.db.domain.JinxiangLogExample;

public interface JinxiangLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    long countByExample(JinxiangLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    int insert(JinxiangLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    JinxiangLog selectOneByExample(JinxiangLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    JinxiangLog selectOneByExampleSelective(@Param("example") JinxiangLogExample example, @Param("selective") JinxiangLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    List<JinxiangLog> selectByExampleSelective(@Param("example") JinxiangLogExample example, @Param("selective") JinxiangLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    List<JinxiangLog> selectByExample(JinxiangLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    JinxiangLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    JinxiangLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    JinxiangLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangLog record, @Param("example") JinxiangLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangLog record, @Param("example") JinxiangLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}