package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangCoupon;
import com.baijuvip.jinxiang.db.domain.JinxiangCouponExample;

public interface JinxiangCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    long countByExample(JinxiangCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    int insert(JinxiangCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    JinxiangCoupon selectOneByExample(JinxiangCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    JinxiangCoupon selectOneByExampleSelective(@Param("example") JinxiangCouponExample example, @Param("selective") JinxiangCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    List<JinxiangCoupon> selectByExampleSelective(@Param("example") JinxiangCouponExample example, @Param("selective") JinxiangCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    List<JinxiangCoupon> selectByExample(JinxiangCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    JinxiangCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    JinxiangCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    JinxiangCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangCoupon record, @Param("example") JinxiangCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangCoupon record, @Param("example") JinxiangCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}