package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangGrouponRules;
import com.baijuvip.jinxiang.db.domain.JinxiangGrouponRulesExample;

public interface JinxiangGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(JinxiangGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    int insert(JinxiangGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    JinxiangGrouponRules selectOneByExample(JinxiangGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    JinxiangGrouponRules selectOneByExampleSelective(@Param("example") JinxiangGrouponRulesExample example, @Param("selective") JinxiangGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    List<JinxiangGrouponRules> selectByExampleSelective(@Param("example") JinxiangGrouponRulesExample example, @Param("selective") JinxiangGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    List<JinxiangGrouponRules> selectByExample(JinxiangGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    JinxiangGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    JinxiangGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    JinxiangGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangGrouponRules record, @Param("example") JinxiangGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangGrouponRules record, @Param("example") JinxiangGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}