package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangStorage;
import com.baijuvip.jinxiang.db.domain.JinxiangStorageExample;

public interface JinxiangStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    long countByExample(JinxiangStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    int insert(JinxiangStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    JinxiangStorage selectOneByExample(JinxiangStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    JinxiangStorage selectOneByExampleSelective(@Param("example") JinxiangStorageExample example, @Param("selective") JinxiangStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    List<JinxiangStorage> selectByExampleSelective(@Param("example") JinxiangStorageExample example, @Param("selective") JinxiangStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    List<JinxiangStorage> selectByExample(JinxiangStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    JinxiangStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    JinxiangStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    JinxiangStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangStorage record, @Param("example") JinxiangStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangStorage record, @Param("example") JinxiangStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}