package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangUserFormid;
import com.baijuvip.jinxiang.db.domain.JinxiangUserFormidExample;

public interface JinxiangUserFormidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    long countByExample(JinxiangUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    int insert(JinxiangUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    JinxiangUserFormid selectOneByExample(JinxiangUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    JinxiangUserFormid selectOneByExampleSelective(@Param("example") JinxiangUserFormidExample example, @Param("selective") JinxiangUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    List<JinxiangUserFormid> selectByExampleSelective(@Param("example") JinxiangUserFormidExample example, @Param("selective") JinxiangUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    List<JinxiangUserFormid> selectByExample(JinxiangUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    JinxiangUserFormid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    JinxiangUserFormid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    JinxiangUserFormid selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangUserFormid record, @Param("example") JinxiangUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangUserFormid record, @Param("example") JinxiangUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}