package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangGoods;
import com.baijuvip.jinxiang.db.domain.JinxiangGoodsExample;

public interface JinxiangGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    long countByExample(JinxiangGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int insert(JinxiangGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    JinxiangGoods selectOneByExample(JinxiangGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    JinxiangGoods selectOneByExampleSelective(@Param("example") JinxiangGoodsExample example, @Param("selective") JinxiangGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    JinxiangGoods selectOneByExampleWithBLOBs(JinxiangGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    List<JinxiangGoods> selectByExampleSelective(@Param("example") JinxiangGoodsExample example, @Param("selective") JinxiangGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    List<JinxiangGoods> selectByExampleWithBLOBs(JinxiangGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    List<JinxiangGoods> selectByExample(JinxiangGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    JinxiangGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    JinxiangGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    JinxiangGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangGoods record, @Param("example") JinxiangGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") JinxiangGoods record, @Param("example") JinxiangGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangGoods record, @Param("example") JinxiangGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(JinxiangGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}