package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangSystem;
import com.baijuvip.jinxiang.db.domain.JinxiangSystemExample;

public interface JinxiangSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    long countByExample(JinxiangSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    int insert(JinxiangSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    JinxiangSystem selectOneByExample(JinxiangSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    JinxiangSystem selectOneByExampleSelective(@Param("example") JinxiangSystemExample example, @Param("selective") JinxiangSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    List<JinxiangSystem> selectByExampleSelective(@Param("example") JinxiangSystemExample example, @Param("selective") JinxiangSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    List<JinxiangSystem> selectByExample(JinxiangSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    JinxiangSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    JinxiangSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    JinxiangSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangSystem record, @Param("example") JinxiangSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangSystem record, @Param("example") JinxiangSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}