package com.baijuvip.jinxiang.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.baijuvip.jinxiang.db.domain.JinxiangCouponUser;
import com.baijuvip.jinxiang.db.domain.JinxiangCouponUserExample;

public interface JinxiangCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(JinxiangCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(JinxiangCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    int insert(JinxiangCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(JinxiangCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    JinxiangCouponUser selectOneByExample(JinxiangCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    JinxiangCouponUser selectOneByExampleSelective(@Param("example") JinxiangCouponUserExample example, @Param("selective") JinxiangCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    List<JinxiangCouponUser> selectByExampleSelective(@Param("example") JinxiangCouponUserExample example, @Param("selective") JinxiangCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    List<JinxiangCouponUser> selectByExample(JinxiangCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    JinxiangCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JinxiangCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    JinxiangCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    JinxiangCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JinxiangCouponUser record, @Param("example") JinxiangCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JinxiangCouponUser record, @Param("example") JinxiangCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JinxiangCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JinxiangCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") JinxiangCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinxiang_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}